---
kind: pipeline
type: docker
name: push-latest-build
steps:
- name: push-latest-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-dump-file-publisher
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  branch:
    - master
---
kind: pipeline
type: docker
name: release
steps:
- name: build-dry-run
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-dump-file-publisher
    dry_run: true
    purge: true
- name: push-tagged-build
  image: plugins/docker
  settings:
    repo: lblod/delta-producer-dump-file-publisher
    tags: ${DRONE_TAG##v}
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    purge: true
trigger:
  event:
    - tag
---
kind: secret
name: docker_username
data: FrZM0kfVDQx32IC6YnwEL0w950DLdokzcqYPtDWv0K4XBtjwW6mdyA==
---
kind: secret
name: docker_password
data: J1oH+BZynm+PHXsWcwAOIqzhYw5AjEJJA9Mmr+NP/s8CJk9R8+Kz4SNqKZgy9Bl9UAOeHiRMSuE56VOvdA4LWg==
---
kind: signature
hmac: a3500f40c0fbc345dbe46037398c546742a077a6015dc2e35a1694a6387c3c45

...
